### ISSUE TITLE
build fails. Missing -ltinfo

### ISSUE THREAD

**Issue by KeesBleijenberg** [judah/haskeline#116] opened 2019-04-15 09:00 UTC
I've moved from Ubuntu 16.0.4 to Mint and want to use vscode
When I do stack install intero I get this error:

--  While building package haskeline-0.7.5.0 using:
      /home/kees/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.4 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.4.0.1 build --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/kees/freeDB/.stack-work/logs/haskeline-0.7.5.0.log

    Configuring haskeline-0.7.5.0...
    Preprocessing library for haskeline-0.7.5.0..
    /usr/bin/ld.gold: error: cannot find -ltinfo
    collect2: error: ld returned 1 exit status
    linking .stack-work/dist/x86_64-linux/Cabal-2.4.0.1/build/System/Console/Haskeline/Directory_hsc_make.o failed (exit code 1)
    command was: /usr/bin/gcc .stack-work/dist/x86_64-linux/Cabal-2.4.0.1/build/System/Console/Haskeline/Directory_hsc_make.o .stack-work/dist/x86_64-linux/Cabal-2.4.0.1/build/System/Console/Haskeline/Directory_hsc_utils.o -o .stack-work/dist/x86_64-linux/Cabal-2.4.0.1/build/System/Console/Haskeline/Directory_hsc_make -fuse-ld=gold -fno-stack-protector -fuse-ld=gold -L/home/kees/.stack/programs/x86_64-linux/ghc-8.6.4/lib/ghc-8.6.4/transformers-0.5.6.2 -Wl,-R,/home/kees/.stack/programs/x86_64-linux/ghc-8.6.4/lib/ghc-8.6.4/transformers-0.5.6.2 -L/home/kees/.stack/programs/x86_64-linux/ghc-8.6.4/lib/ghc-8.6.4/terminfo-0.4.1.2 -Wl,-R,/home/kees/.stack/programs/x86_64-linux/ghc-8.6.4/lib/ghc-8.6.4/terminfo-0.4.1.2 -ltinfo -L/home/kees/.stack/programs/x86_64-linux/ghc-8.6.4/lib/ghc-8.6.4/stm-2.5.0.0 -Wl,-R,/home/kees/.stack/programs/x86_64-linux/ghc-8.6.4/lib/ghc-8.6.4/stm-2.5.0.0 -L/home/kees/.stack/programs/x86_64-linux/ghc-8.6.4/lib/ghc-8.6.4/process-1.6.5.0 -Wl,-R,/home/kees/.stack/programs/x86_64-linux/ghc-8.6.4/lib/ghc-8.6.4/process-1.6.5.0 -L/home/kees/.stack/programs/x86_64-linux/ghc-8.6.4/lib/ghc-8.6.4/directory-1.3.3.0 -Wl,-R,/home/kees/.stack/programs/x86_64-linux/ghc-8.6.4/lib/ghc-8.6.4/directory-1.3.3.0 -L/home/kees/.stack/programs/x86_64-linux/ghc-8.6.4/lib/ghc-8.6.4/unix-2.7.2.2 -Wl,-R,/home/kees/.stack/programs/x86_64-linux/ghc-8.6.4/lib/ghc-8.6.4/unix-2.7.2.2 -lrt -lutil -ldl -lpthread -L/home/kees/.stack/programs/x86_64-linux/ghc-8.6.4/lib/ghc-8.6.4/time-1.8.0.2 -Wl,-R,/home/kees/.stack/programs/x86_64-linux/ghc-8.6.4/lib/ghc-8.6.4/time-1.8.0.2 -L/home/kees/.stack/programs/x86_64-linux/ghc-8.6.4/lib/ghc-8.6.4/filepath-1.4.2.1 -Wl,-R,/home/kees/.stack/programs/x86_64-linux/ghc-8.6.4/lib/ghc-8.6.4/filepath-1.4.2.1 -L/home/kees/.stack/programs/x86_64-linux/ghc-8.6.4/lib/ghc-8.6.4/containers-0.6.0.1 -Wl,-R,/home/kees/.stack/programs/x86_64-linux/ghc-8.6.4/lib/ghc-8.6.4/containers-0.6.0.1 -L/home/kees/.stack/programs/x86_64-linux/ghc-8.6.4/lib/ghc-8.6.4/bytestring-0.10.8.2 -Wl,-R,/home/kees/.stack/programs/x86_64-linux/ghc-8.6.4/lib/ghc-8.6.4/bytestring-0.10.8.2 -L/home/kees/.stack/programs/x86_64-linux/ghc-8.6.4/lib/ghc-8.6.4/deepseq-1.4.4.0 -Wl,-R,/home/kees/.stack/programs/x86_64-linux/ghc-8.6.4/lib/ghc-8.6.4/deepseq-1.4.4.0 -L/home/kees/.stack/programs/x86_64-linux/ghc-8.6.4/lib/ghc-8.6.4/array-0.5.3.0 -Wl,-R,/home/kees/.stack/programs/x86_64-linux/ghc-8.6.4/lib/ghc-8.6.4/array-0.5.3.0 -L/home/kees/.stack/programs/x86_64-linux/ghc-8.6.4/lib/ghc-8.6.4/base-4.12.0.0 -Wl,-R,/home/kees/.stack/programs/x86_64-linux/ghc-8.6.4/lib/ghc-8.6.4/base-4.12.0.0 -L/home/kees/.stack/programs/x86_64-linux/ghc-8.6.4/lib/ghc-8.6.4/integer-gmp-1.0.2.0 -Wl,-R,/home/kees/.stack/programs/x86_64-linux/ghc-8.6.4/lib/ghc-8.6.4/integer-gmp-1.0.2.0 -lgmp -L/home/kees/.stack/programs/x86_64-linux/ghc-8.6.4/lib/ghc-8.6.4/ghc-prim-0.5.3 -Wl,-R,/home/kees/.stack/programs/x86_64-linux/ghc-8.6.4/lib/ghc-8.6.4/ghc-prim-0.5.3 -L/home/kees/.stack/programs/x86_64-linux/ghc-8.6.4/lib/ghc-8.6.4/rts -Wl,-R,/home/kees/.stack/programs/x86_64-linux/ghc-8.6.4/lib/ghc-8.6.4/rts -lm -lrt -ldl -lpthread

I'am using stack version 1.9.3 and resolver lts-13.16
What can I do?

Kees

**Comment by judah** [comment] 2019-04-17 16:38
See the following link; you probably need to `sudo apt-get install libtinfo-dev`:
https://github.com/chrisdone/intero/issues/243
Closing as a duplicate of that one, but let me know if you still run into problems.

**Closed by judah** 2019-04-17 16:38 UTC
